### ISSUE TITLE
make up fails to load pypy

### ISSUE THREAD

**Issue by stevethibault** [sebiwi/kubernetes-coreos#6]
I'm running on ubuntu 18.04. I've installed the latest ansible 2.03, and the latest vagrant. 

I'm running into an error that seems to be related to the latest coreos and a shared library that has moved. Pardon my short post. Please let me know what further information you need and if you could a bit of help as to how to collect it properly.

The errors: 
$ make up
Bringing machine 'etcd-01' up with 'virtualbox' provider...
Bringing machine 'kube-master-01' up with 'virtualbox' provider...
Bringing machine 'kube-worker-01' up with 'virtualbox' provider...
Bringing machine 'kube-worker-02' up with 'virtualbox' provider...
==> etcd-01: Importing base box 'coreos-stable'...
==> etcd-01: Matching MAC address for NAT networking...
==> etcd-01: Checking if box 'coreos-stable' is up to date...
==> etcd-01: Setting the name of the VM: kubernetes-coreos_etcd-01_1538648738057_3874
==> etcd-01: Clearing any previously set network interfaces...
==> etcd-01: Preparing network interfaces based on configuration...
    etcd-01: Adapter 1: nat
    etcd-01: Adapter 2: hostonly
==> etcd-01: Forwarding ports...
    etcd-01: 22 (guest) => 2222 (host) (adapter 1)
==> etcd-01: Running 'pre-boot' VM customizations...
==> etcd-01: Booting VM...
==> etcd-01: Waiting for machine to boot. This may take a few minutes...
    etcd-01: SSH address: 127.0.0.1:2222
    etcd-01: SSH username: core
    etcd-01: SSH auth method: private key
==> etcd-01: Machine booted and ready!
==> etcd-01: Setting hostname...
==> etcd-01: Configuring and enabling network interfaces...
==> etcd-01: [vagrant-hostmanager:guests] Updating hosts file on active guest virtual machines...
==> kube-master-01: Importing base box 'coreos-stable'...
==> kube-master-01: Matching MAC address for NAT networking...
==> kube-master-01: Checking if box 'coreos-stable' is up to date...
==> kube-master-01: Setting the name of the VM: kubernetes-coreos_kube-master-01_1538648769073_26537
==> kube-master-01: Fixed port collision for 22 => 2222. Now on port 2200.
==> kube-master-01: Clearing any previously set network interfaces...
==> kube-master-01: Preparing network interfaces based on configuration...
    kube-master-01: Adapter 1: nat
    kube-master-01: Adapter 2: hostonly
==> kube-master-01: Forwarding ports...
    kube-master-01: 22 (guest) => 2200 (host) (adapter 1)
==> kube-master-01: Running 'pre-boot' VM customizations...
==> kube-master-01: Booting VM...
==> kube-master-01: Waiting for machine to boot. This may take a few minutes...
    kube-master-01: SSH address: 127.0.0.1:2200
    kube-master-01: SSH username: core
    kube-master-01: SSH auth method: private key
==> kube-master-01: Machine booted and ready!
==> kube-master-01: Setting hostname...
==> kube-master-01: Configuring and enabling network interfaces...
==> kube-master-01: [vagrant-hostmanager:guests] Updating hosts file on active guest virtual machines...
==> kube-worker-01: Importing base box 'coreos-stable'...
==> kube-worker-01: Matching MAC address for NAT networking...
==> kube-worker-01: Checking if box 'coreos-stable' is up to date...
==> kube-worker-01: Setting the name of the VM: kubernetes-coreos_kube-worker-01_1538648800317_58007
==> kube-worker-01: Fixed port collision for 22 => 2222. Now on port 2201.
==> kube-worker-01: Clearing any previously set network interfaces...
==> kube-worker-01: Preparing network interfaces based on configuration...
    kube-worker-01: Adapter 1: nat
    kube-worker-01: Adapter 2: hostonly
==> kube-worker-01: Forwarding ports...
    kube-worker-01: 22 (guest) => 2201 (host) (adapter 1)
==> kube-worker-01: Running 'pre-boot' VM customizations...
==> kube-worker-01: Booting VM...
==> kube-worker-01: Waiting for machine to boot. This may take a few minutes...
    kube-worker-01: SSH address: 127.0.0.1:2201
    kube-worker-01: SSH username: core
    kube-worker-01: SSH auth method: private key
==> kube-worker-01: Machine booted and ready!
==> kube-worker-01: Setting hostname...
==> kube-worker-01: Configuring and enabling network interfaces...
==> kube-worker-01: [vagrant-hostmanager:guests] Updating hosts file on active guest virtual machines...
==> kube-worker-02: Importing base box 'coreos-stable'...
==> kube-worker-02: Matching MAC address for NAT networking...
==> kube-worker-02: Checking if box 'coreos-stable' is up to date...
==> kube-worker-02: Setting the name of the VM: kubernetes-coreos_kube-worker-02_1538648833559_95118
==> kube-worker-02: Fixed port collision for 22 => 2222. Now on port 2202.
==> kube-worker-02: Clearing any previously set network interfaces...
==> kube-worker-02: Preparing network interfaces based on configuration...
    kube-worker-02: Adapter 1: nat
    kube-worker-02: Adapter 2: hostonly
==> kube-worker-02: Forwarding ports...
    kube-worker-02: 22 (guest) => 2202 (host) (adapter 1)
==> kube-worker-02: Running 'pre-boot' VM customizations...
==> kube-worker-02: Booting VM...
==> kube-worker-02: Waiting for machine to boot. This may take a few minutes...
    kube-worker-02: SSH address: 127.0.0.1:2202
    kube-worker-02: SSH username: core
    kube-worker-02: SSH auth method: private key
==> kube-worker-02: Machine booted and ready!
==> kube-worker-02: Setting hostname...
==> kube-worker-02: Configuring and enabling network interfaces...
==> kube-worker-02: [vagrant-hostmanager:guests] Updating hosts file on active guest virtual machines...
 _______________________________
< PLAY [Bootstrap coreos hosts] >
 -------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 ________________________________________________________
/ TASK [bootstrap/ansible-bootstrap : Check if Python is \
\ installed]                                             /
 --------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [etcd-01]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 127, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "bash: /home/core/bin/python: No such file or directory\r\n", "stdout_lines": ["bash: /home/core/bin/python: No such file or directory"]}
...ignoring
fatal: [kube-master-01]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 127, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "bash: /home/core/bin/python: No such file or directory\r\n", "stdout_lines": ["bash: /home/core/bin/python: No such file or directory"]}
...ignoring
fatal: [kube-worker-01]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 127, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "bash: /home/core/bin/python: No such file or directory\r\n", "stdout_lines": ["bash: /home/core/bin/python: No such file or directory"]}
...ignoring
fatal: [kube-worker-02]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 127, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "bash: /home/core/bin/python: No such file or directory\r\n", "stdout_lines": ["bash: /home/core/bin/python: No such file or directory"]}
...ignoring
 __________________________________________________________
/ TASK [bootstrap/ansible-bootstrap : Check if install tar \
\ file exists]                                             /
 ----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [etcd-01]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "stat: cannot stat '/tmp/pypy-5.1.0.tar.bz2': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/tmp/pypy-5.1.0.tar.bz2': No such file or directory"]}
...ignoring
fatal: [kube-master-01]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "stat: cannot stat '/tmp/pypy-5.1.0.tar.bz2': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/tmp/pypy-5.1.0.tar.bz2': No such file or directory"]}
...ignoring
fatal: [kube-worker-02]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "stat: cannot stat '/tmp/pypy-5.1.0.tar.bz2': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/tmp/pypy-5.1.0.tar.bz2': No such file or directory"]}
...ignoring
fatal: [kube-worker-01]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "stat: cannot stat '/tmp/pypy-5.1.0.tar.bz2': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/tmp/pypy-5.1.0.tar.bz2': No such file or directory"]}
...ignoring
 _____________________________________________________________
/ TASK [bootstrap/ansible-bootstrap : Check if pypy directory \
\ exists]                                                     /
 -------------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [etcd-01]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "stat: cannot stat '/home/core/pypy': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/home/core/pypy': No such file or directory"]}
...ignoring
fatal: [kube-worker-01]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "stat: cannot stat '/home/core/pypy': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/home/core/pypy': No such file or directory"]}
...ignoring
fatal: [kube-master-01]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "stat: cannot stat '/home/core/pypy': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/home/core/pypy': No such file or directory"]}
...ignoring
fatal: [kube-worker-02]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "stat: cannot stat '/home/core/pypy': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/home/core/pypy': No such file or directory"]}
...ignoring
 __________________________________________________________
/ TASK [bootstrap/ansible-bootstrap : Check if libtinfo is \
\ simlinked]                                               /
 ----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [kube-master-01]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "stat: cannot stat '/home/core/pypy/lib/libtinfo.so.5': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/home/core/pypy/lib/libtinfo.so.5': No such file or directory"]}
...ignoring
fatal: [etcd-01]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "stat: cannot stat '/home/core/pypy/lib/libtinfo.so.5': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/home/core/pypy/lib/libtinfo.so.5': No such file or directory"]}
...ignoring
fatal: [kube-worker-01]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "stat: cannot stat '/home/core/pypy/lib/libtinfo.so.5': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/home/core/pypy/lib/libtinfo.so.5': No such file or directory"]}
...ignoring
fatal: [kube-worker-02]: FAILED! => {"changed": false, "msg": "non-zero return code", "rc": 1, "stderr": "Connection to 127.0.0.1 closed.\r\n", "stdout": "stat: cannot stat '/home/core/pypy/lib/libtinfo.so.5': No such file or directory\r\n", "stdout_lines": ["stat: cannot stat '/home/core/pypy/lib/libtinfo.so.5': No such file or directory"]}
...ignoring
 ____________________________________________________
< TASK [bootstrap/ansible-bootstrap : Download PyPy] >
 ----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [etcd-01]
changed: [kube-worker-02]
changed: [kube-worker-01]
changed: [kube-master-01]
 ___________________________________________________
< TASK [bootstrap/ansible-bootstrap : Extract PyPy] >
 ---------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [kube-worker-01]
changed: [kube-master-01]
changed: [kube-worker-02]
changed: [etcd-01]
 ___________________________________________________________
/ TASK [bootstrap/ansible-bootstrap : Symlink libncurses as \
\ libtinfo.so.5]                                            /
 -----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [kube-worker-01]
changed: [kube-worker-02]
changed: [kube-master-01]
changed: [etcd-01]
 ___________________________________________________
< TASK [bootstrap/ansible-bootstrap : Install PyPy] >
 ---------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` 
instead use `result is failed`. This feature will be removed in version 2.9. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [kube-worker-02]
changed: [kube-master-01]
changed: [kube-worker-01]
changed: [etcd-01]
 _______________________________________________________
/ TASK [bootstrap/ansible-bootstrap : Test if Python is \
\ installed]                                            /
 -------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [kube-worker-02]: FAILED! => {"changed": false, "module_stderr": "Connection to 127.0.0.1 closed.\r\n", "module_stdout": "/home/core/pypy/bin/pypy: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory\r\n", "msg": "MODULE FAILURE", "rc": 127}
fatal: [kube-master-01]: FAILED! => {"changed": false, "module_stderr": "Connection to 127.0.0.1 closed.\r\n", "module_stdout": "/home/core/pypy/bin/pypy: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory\r\n", "msg": "MODULE FAILURE", "rc": 127}
fatal: [etcd-01]: FAILED! => {"changed": false, "module_stderr": "Connection to 127.0.0.1 closed.\r\n", "module_stdout": "/home/core/pypy/bin/pypy: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory\r\n", "msg": "MODULE FAILURE", "rc": 127}
fatal: [kube-worker-01]: FAILED! => {"changed": false, "module_stderr": "Connection to 127.0.0.1 closed.\r\n", "module_stdout": "/home/core/pypy/bin/pypy: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory\r\n", "msg": "MODULE FAILURE", "rc": 127}
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

etcd-01                    : ok=8    changed=4    unreachable=0    failed=1   
kube-master-01             : ok=8    changed=4    unreachable=0    failed=1   
kube-worker-01             : ok=8    changed=4    unreachable=0    failed=1   
kube-worker-02             : ok=8    changed=4    unreachable=0    failed=1   

Makefile:10: recipe for target 'playbook' failed
make: *** [playbook] Error 2

**Comment by stevethibault** [comment]
I am very new to ansible, vagrant, and core os. This is my first foray into all of these. So I am not sure how to start debugging or finding logs.

**Comment by stevethibault** [comment]
So it appears that the step in configure.yml in the roles/bootstrap/ansible-bootstrap/tasks folder is behind compared on coreos. 

There is no file /lib64/libncurses.so.5.9 in the coreos image, however there is libncurses.so.6.1. Should I just update the task "Symlink libncurses as libtinvo.so.5 to point to the existing libncurses library?

That doesn't seem like a good idea, its a new version. What will happen? Should I also update the pypy_version to something newer?

**Comment by stevethibault** [comment]
So I've updated the link to libncurses to be from /lib64/libncurses.so.6.1 and still to libtnvo.so.5, and that gets past the pypy install and tests. However, the coreos image is now shipped with etcd3, which doesn't seem to need a separate container. Instead it seems you configure a service on each node in the cluster and prime it with all of the nodes known in the cluster initially either through the container linux config yml, which isn't relevant here, or a systemd service unit that has a number of parameters, including either a public core os discovery service, or by setting the ip's manually among a number of other parameters. I think the latter here would make the most sense given a pre-set box image is downloaded and updated. 
Details are here: https://github.com/etcd-io/etcd/blob/master/Documentation/platforms/container-linux-systemd.md

I'd love to work on the update, but this is turning out to be a bit too advanced for me. I am hoping a more experienced coreos person can step in here?

**Comment by sebiwi** [comment]
Hi Steve,

Yeah, it seems that I'm scanning for files that are no longer present on Container Linux. I'll fix that ASAP.

There is also the thing regarding etcd3. That one will take a bit longer.

**Comment by stevethibault** [comment]
That’s cool! I’m super excited anybody is looking at it. Thank you!!!

**Comment by sebiwi** [comment]
This is fixed by commit 420d5d6.
